/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhispersRouteImport } from './routes/whispers'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OthersRouteImport } from './routes/others'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as OthersWorkingExperienceRouteImport } from './routes/others.working-experience'
import { Route as OthersPhotographyRouteImport } from './routes/others.photography'

const WhispersRoute = WhispersRouteImport.update({
  id: '/whispers',
  path: '/whispers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OthersRoute = OthersRouteImport.update({
  id: '/others',
  path: '/others',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const OthersWorkingExperienceRoute = OthersWorkingExperienceRouteImport.update({
  id: '/working-experience',
  path: '/working-experience',
  getParentRoute: () => OthersRoute,
} as any)
const OthersPhotographyRoute = OthersPhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => OthersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/others': typeof OthersRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/whispers': typeof WhispersRoute
  '/others/photography': typeof OthersPhotographyRoute
  '/others/working-experience': typeof OthersWorkingExperienceRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/others': typeof OthersRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/whispers': typeof WhispersRoute
  '/others/photography': typeof OthersPhotographyRoute
  '/others/working-experience': typeof OthersWorkingExperienceRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/others': typeof OthersRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/whispers': typeof WhispersRoute
  '/others/photography': typeof OthersPhotographyRoute
  '/others/working-experience': typeof OthersWorkingExperienceRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/others'
    | '/projects'
    | '/whispers'
    | '/others/photography'
    | '/others/working-experience'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/others'
    | '/projects'
    | '/whispers'
    | '/others/photography'
    | '/others/working-experience'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/others'
    | '/projects'
    | '/whispers'
    | '/others/photography'
    | '/others/working-experience'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  OthersRoute: typeof OthersRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  WhispersRoute: typeof WhispersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whispers': {
      id: '/whispers'
      path: '/whispers'
      fullPath: '/whispers'
      preLoaderRoute: typeof WhispersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/others': {
      id: '/others'
      path: '/others'
      fullPath: '/others'
      preLoaderRoute: typeof OthersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/others/working-experience': {
      id: '/others/working-experience'
      path: '/working-experience'
      fullPath: '/others/working-experience'
      preLoaderRoute: typeof OthersWorkingExperienceRouteImport
      parentRoute: typeof OthersRoute
    }
    '/others/photography': {
      id: '/others/photography'
      path: '/photography'
      fullPath: '/others/photography'
      preLoaderRoute: typeof OthersPhotographyRouteImport
      parentRoute: typeof OthersRoute
    }
  }
}

interface OthersRouteChildren {
  OthersPhotographyRoute: typeof OthersPhotographyRoute
  OthersWorkingExperienceRoute: typeof OthersWorkingExperienceRoute
}

const OthersRouteChildren: OthersRouteChildren = {
  OthersPhotographyRoute: OthersPhotographyRoute,
  OthersWorkingExperienceRoute: OthersWorkingExperienceRoute,
}

const OthersRouteWithChildren =
  OthersRoute._addFileChildren(OthersRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  OthersRoute: OthersRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  WhispersRoute: WhispersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
